### ISSUE TITLE
import pandas as pd

### ISSUE THREAD

**Issue by michaelpalumbo** [gr33ndata/gitzicht#1]
When running "python gogitzicht.py -i input.log -o output.csv"

I receive the following error:

Traceback (most recent call last):
  File "gogitzicht.py", line 4, in <module>
    from gitzicht import *
  File "/Users/mp/gitzicht/gitzicht/__init__.py", line 7, in <module>
    from pivot import Pivot
  File "/Users/mp/gitzicht/gitzicht/pivot.py", line 1, in <module>
    import pandas as pd
ImportError: No module named pandas

Can you point me to a solution? Thanks!

**Comment by michaelpalumbo** [comment]
ah, nevermind, I solved it. So pandas is a lib in python, as noted in the import in pivot.py.
